gui:
  switchTabsWithPanelJumpKeys: true
git:
  autoForwardBranches: none
  autoFetch: false
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
