theme = "native"
icons = "material-nf"

# [[block]]
# block = "custom"
# shell = "sh"
# # can't show {{position}} for spotify..
# command = "playerctl --player=spotify metadata --format '{{artist}} - {{title}} [{{status}}]'"
# on_click = "playerctl --player=spotify play-pause"
# interval = 5

[[block]]
block = "music"
player = "spotify"
buttons = ["play"]
on_collapsed_click = "spotify"
on_click = "playerctl --player=spotify play-pause"

[[block]]
block = "custom"
# shell = "sh"
# command = 'echo "n:$(dunstctl count history)/$(dunstctl count displayed)"'
command = 'echo "n"'
on_click = "dunstctl history | code -"
# interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 30
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
interval = 10

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "load"
interval = 5
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%Y-%m-%d %T"
